### PR TITLE
Added placeholder label on top of value for iOS and Android 😉

### PR DESCRIPTION
**Pull request by FRizzonelli**
Hi @markuswind,

I've implemented a new feature, now you can pass a placeholder property to the picker, and it'll render it above the selected value. This is useful if you need to style your select component like other inputs in your view. 
You can also pass a placeholderStyle property to customize the label!

Please let me know if you find it useful and if you can merge it :)

### CODE REVIEW

**Comment by markuswind** [comment]
Thanks, it might be useful! But wouldn't it be better to pass a render function, so then it wouldn't be limited to a Text component?

**Comment by mikerodham** [comment]
@markuswind @FRizzonelli any movement on this? Desperately wanting this!

**Comment by FRizzonelli** [comment]
@mikerodham Will try to fix the PR in few days!

**Comment by mikerodham** [comment]
I've solved this issue by wrapping the Input with a View and embedding a conditional Text component.

```
<View key={j}>
    {this.state.selected.length === 0 &&
        <Text style={{position: 'relative', fontSize: 18, top: 25, left: 10}}>
            Please select an item
        </Text>
    }

    <SelectInput
           value={this.state.selected}
           options={this.getPickerOptions(i, j)}
           onSubmitEditing={(val) => {
                this.setState({selected: val})
           }}
           style={[styles.selectInput, styles.selectInputSmall]}
           labelStyle={{fontSize: 15}}
       />
</View>
```

**Comment by saikiranoptisol** [comment]
> I've solved this issue by wrapping the Input with a View and embedding a conditional Text component.
> 
> ```
> <View key={j}>
>     {this.state.selected.length === 0 &&
>         <Text style={{position: 'relative', fontSize: 18, top: 25, left: 10}}>
>             Please select an item
>         </Text>
>     }
> 
>     <SelectInput
>            value={this.state.selected}
>            options={this.getPickerOptions(i, j)}
>            onSubmitEditing={(val) => {
>                 this.setState({selected: val})
>            }}
>            style={[styles.selectInput, styles.selectInputSmall]}
>            labelStyle={{fontSize: 15}}
>        />
> </View>
> ```

what is i there @mikerodham

**Comment by markuswind** [comment]
Closing this because I think this can be achieved without changes inside the library itself.

**Pull request closed without merging**
